### ISSUE TITLE
Backlight issue

### ISSUE THREAD

**Issue by Tr4um4z** [ingbenna/AZ-Touch_esphome_thermostat#2]
Ciao
Bel lavoro!
I'm working in a projet like your but i have problem with backlight.
simply it doesn't turn off on GPIO15. the board from az-delivery is complete or i have to solder some transistor to make brightness work?
Thanks in advance

![IMG20230209175006](https://user-images.githubusercontent.com/82873922/217882915-349f75ea-e738-43cf-9982-f2967a22d830.jpg)

**Comment by ingbenna** [comment]
Ciao e grazie!
Nulla da saldare, è stato fatto semplicemente a livello di codice.

**Comment by Tr4um4z** [comment]
dopo mille imprecazioni a me funziona solo uncommentando led_pin sotto display

`display:
  - platform: ili9341
    model: TFT_2.4
    id: touch_display
    rotation: 90
    cs_pin: GPIO5
    dc_pin: GPIO4 
    #led_pin: GPIO15
    reset_pin: GPIO22`

**Comment by ingbenna** [comment]
Uhm, a codice non è commentato sul repo :)
Ottimo così comunque, grazie per il contributo :)

**Comment by Tr4um4z** [comment]
Un altra cosa che non capisco è come mai 

[15:46:19][D][light:035]: 'Retroilluminazione display' Setting:
[15:46:19][D][light:046]:   State: ON
[15:46:19][D][light:084]:   Transition length: 1.0s

va su state ON solo al primo tocco a display spento
dopodichè i successivi tocchi:

[15:47:10][D][light:035]: 'Retroilluminazione display' Setting:
[15:47:10][D][light:084]:   Transition length: 1.0s

non REimposta lo State ON e quindi in pratica il delay di 60 secondi per lo spegnimento parte dal primo tocco in pratica.
Secondo te cosa può essere?

**Comment by ingbenna** [comment]
E' un comportamento voluto:
- se il display è spento: il tocco lo fa accendere;
- se il display è acceso: il tocco viene usato per attivare i virtual buttons.

Il tutto è pilotato dalla variabile globale seguente:

globals:
    - id: climate_thermostat_preset_override
      type: bool
      restore_value: yes

**Comment by DragonflyNet67** [comment]
Hi, i have the same AZ Touch mod Case with the 2.8" Screen. You wrote, that you attached a DS3231 RTC. Could you please tell me where you connected the SDA and SCL Lines and how you got the RTC working (which Library). As per Schematic from AZ-Delivery of this Case SDA Pin 21 is connected to the Beeper and SCL Pin 22 is connected to the TFT-Reset. 
Thank you very much
