### ISSUE TITLE
DS3231 SCL/SDA Connection on AZ Touch Mod?

### ISSUE THREAD

**Issue by DragonflyNet67** [ingbenna/AZ-Touch_esphome_thermostat#3]
Hi, i have the same AZ Touch mod Case with the 2.8" Screen. You wrote, that you attached a DS3231 RTC. Could you please tell me where you connected the SDA and SCL Lines and how you got the RTC working (which Library). As per Schematic from AZ-Delivery of this Case SDA Pin 21 is connected to the Beeper and SCL Pin 22 is connected to the TFT-Reset. 
Thank you very much

**Comment by ingbenna** [comment]
Hi!
I have used esphome framework that embed all needed libraries.

Then the used pin for i2c (the protocol used by etc):
- sda: 25
- scl: 26

**Comment by DragonflyNet67** [comment]
Thank you very much. did you attach your BMP280 using I2C also on SDA 25 and SCL 26? If so, how did you solder it on the PCB?
I'd really appreciate it if you could give me a hint on how to solder the RTC SDA/SCL and BMP280 SDA/SCL on the same PCB hole.

**Comment by ingbenna** [comment]
Hi!
Yes, the I2C is a bus so you can attach several devices in parallel (each one will have a different address used by microcontroller).
I do not solder them directly but I used a breadboard connected with two little cables! 😊

**Comment by DragonflyNet67** [comment]
Thank you very much. I thought you soldered both I2C devices into the PCB Pins marked as I25 and I26.
I Prototyped on a breadboard both devices (RTC DS3231 and BME280) on these two pins using Wire (works perfectly). Now I have no idea how to add some pinheaders or other solution for 2 or maybe 3 I2C devices (2 at the moment but having 1 left for later)
![PCB_Bottom](https://github.com/user-attachments/assets/a27c6284-3e51-4864-ac08-1935cfe60094)

Thank you very much for your help. Many regards
